resolver: lts-18.21

packages:
- .

allow-newer: true

flags:
#  hid-examples:
#    with-pg: True

extra-deps:
  - Chart-diagrams-1.9.3
  - HDBC-postgresql-2.4.0.0
  - SVGFonts-1.7.0.1
  - active-0.2.0.15
  - blaze-colonnade-1.2.2.1
  - colonnade-1.2.0.2
  - diagrams-core-1.5.0
  - diagrams-lib-1.4.5.1
  - diagrams-postscript-1.5
  - diagrams-svg-1.4.3.1
  - dual-tree-0.2.3.0
  - fast-builder-0.1.3.0
  - hasql-th-0.4.0.10
  - headed-megaparsec-0.2.0.2
  - json-stream-0.4.2.4
  - monoid-extras-0.6.1
  - postgresql-syntax-0.4
  - statestack-0.3
  - streaming-utils-0.2.1.0
  - svg-builder-0.1.1
  - template-haskell-compat-v0208-0.1.5
